services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:MyStrongP@ssw0rd!@77.237.232.243:5432/guiaseller"
      PORT: 8080
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyStrongP@ssw0rd!
      POSTGRES_DB: guiaseller
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
